### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [Alnoir-0011/coffee_review_app#93]
MVPリリースお疲れ様でした。
挙動の確認を行いました。LGTMです。
より良いものにするための改善点をお伝えします。

---

使用している技術等からそちらの方は一定水準に達しているかと感じました。
ただ、見た目やユーザーが使う導線の印象が良くなく、折角技術力がある状態なのに、そうした部分でマイナスの印象を抱かれてしまう状態に見えました。

■初期データを拡充させましょう（画像付き）
トップページに訪れた際に、どういったことができるサービスなのかが分かりづらいため、初期データを拡充させてユーザーにどんなサービスなのかが直感的に分かるようにしましょう。

■Googleログイン有効化
Googleログインを行うと以下の画像ページが出てしまいます。対応してログインできるようにしましょう。
![スクリーンショット 2024-01-31 20 14 19](https://github.com/Alnoir-0011/coffee_review_app/assets/61481161/397b93ae-bd7b-409b-91c5-84c6b695dd23)

■頻繁にエラー画面に出くわす体験を解消
- https://www.coffeestacklog.com/beans/6
他者の投稿詳細を開こうとするとエラーが出てしまう？？。一度アカウントを切り替えるなどして挙動の確認をしてください。

■登録の動線の見直し
ログイン後のユーザーには以下のことは分かりますが、それ以外の購入記録を付ける導線が分からない状態に見受けられました。トップページからどういったことができるサービスなのかが伝わるようにボタンを配置したほうが良いかと感じました。

- トップページから何某かの検索ができることがわかる
- ヘッダーのShepから何某かのお店情報を得られることがわかる
- ヘッダーのマイページからユーザー情報周りに関するページへ遷移することがわかる

■購入記録を簡単に登録できるようにする
現状、マイページ→購入記録を登録する→購入記録作成ページへ遷移してフォームに値を入れていきます動線になっているので、上記に記載した通り、トップページからでも該当ページへ遷移できるようにしましょう。

また、入力フォームに値を入れていく中で"登録する"ボタンを押して初めて先に店舗やコーヒー豆を登録していないと、購入記録作成ができないというのが分かる状態になっており、ユーザーからするとその体験だけで、このサービスから離脱してしまうのではないかと感じました。

同一ページ内で登録できるようにするなど、改善を行った方が良いかと感じました。

■Shopの検索機能
ここで検索するとお店が表示されることをユーザーは期待しているかと思います。ただ現状はサービスを利用しているユーザーがお店を登録していくことで、ここの検索が機能していく形になっており、ログイン直後にShopへ遷移して検索を行ったユーザーからすると、何を検索してくれたのかが分からず、ある種放置されているように感じてしまうかと思いました。初期データの拡充と合わせて、どういった検索機能なのかがユーザーに伝わるようにしましょう。

---

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。

看板は以下を参考に1週間を単位とした列を作成して、そこに各issueを配置してください。
https://github.com/users/Tsuchiya2/projects/2

また書き出したissueをもとに修正完了までのスケジュール、本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by Alnoir-0011** [comment]
MVPレビューありがとうございます！
修正予定の内容を下記の通りissueとして展開し、GitHubProjectに配置済みです。
- [Reviewモデルへ画像カラムの追加、Beanモデルから画像カラムの削除 ](https://github.com/Alnoir-0011/coffee_review_app/issues/100)
- [トップページの表示内容を変更](https://github.com/Alnoir-0011/coffee_review_app/issues/98)
- [店舗一覧機能に現在の検索内容の説明を追加 #97](https://github.com/Alnoir-0011/coffee_review_app/issues/97)
- [購入記録作成への導線追加、コーヒー豆登録を同一ページでモーダル化 #94](https://github.com/Alnoir-0011/coffee_review_app/issues/94)

修正完了予定は2/11、本リリースは2/20を予定しています。
